alias: 'Bedhead turn white max'
initial_state: 'on'
trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      scene_id: 20
      entity_id: zwave.nodon_crc3100_octan_remote
action:
  - service: light.turn_on
    data:
      entity_id: light.yeelight_strip1_286c07afc307
      color_name: "white"
      brightness: 255
