alias: 'Bedhead turn off'
initial_state: 'on'
trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      scene_id: 30
      entity_id: zwave.nodon_crc3100_octan_remote
condition:
  - condition: state
    state: 'on'
    entity_id: light.yeelight_strip1_286c07afc307
action:
  - service: light.turn_off
    data:
      entity_id: light.yeelight_strip1_286c07afc307
