alias: 'Bedhead turn on red'
initial_state: 'on'
trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      scene_id: 40
      entity_id: zwave.nodon_crc3100_octan_remote
action:
  - service: switch.turn_off
    entity_id: switch.circadian_lighting_circadian_master_bedroom
  - service: light.turn_on
    data:
      entity_id: light.yeelight_strip1_286c07afc307
      color_name: "red"
      brightness_pct: 2
