alias: 'Bedhead turn on warm'
initial_state: 'on'
trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      scene_id: 23
      entity_id: zwave.nodon_crc3100_octan_remote
action:
  - service: light.turn_on
    data:
      entity_id: light.yeelight_strip1_286c07afc307
      color_temp: 500
