initial_state: 'on'
alias: 'Living room dark motion'
trigger:
  platform: state
  entity_id: binary_sensor.pi3_living_room_motion
  to: 'on'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: input_boolean.livingroom_lights_auto
      state: 'on'
    - condition: state
      entity_id: timer.living_room_motion
      state: 'active'
action:
  - service: timer.start
    data:
      entity_id: timer.living_room_motion
      duration: '00:02:00'
