initial_state: 'on'
alias: 'Vestibule mode away'
trigger:
  - platform: state
    entity_id: input_boolean.home_occupied
    to: 'off'
condition:
  - condition: template
    value_template: "{{ not is_state('input_select.vestibule','Away') }}"
  # Christmas!
  - condition: state
    entity_id: input_select.season
    state: 'Christmas'
action:
  - service: input_select.select_option
    data:
      entity_id: 'input_select.vestibule'
      option: 'Away'
