alias: 'person1 bedside turn off'
initial_state: 'on'
trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      scene_id: 30
      entity_id: zwave.green_remote
condition:
  - condition: state
    state: 'on'
    entity_id: light.yeelight_strip1_7811dca22b87
action:
  - service: light.turn_off
    data:
      entity_id: light.yeelight_strip1_7811dca22b87
  - delay: '00:01:00'
  - condition: state
    entity_id: light.yeelight_strip1_7811dca22b87
    state: 'on'
  - service: light.turn_off
    data:
      entity_id: light.yeelight_strip1_7811dca22b87
      transition: 30
