alias: 'Christmas lights off season'
initial_state: 'on'
trigger:
  - platform: state
    entity_id: input_select.season
    from: 'Christmas'
condition:
  - condition: state
    entity_id: input_boolean.lighting_automations
    state: 'on'
action:
  - service: switch.turn_off
    entity_id:
      - switch.pi3_family_room_socket_switch
      - switch.pi3_cabinet_light_switch
      - switch.pi3_vestibule_switch
      - switch.pi3_hall_downstairs_switch
  - delay: '00:01:00'
  - service: switch.turn_off
    entity_id:
      - switch.pi3_family_room_socket_switch
      - switch.pi3_cabinet_light_switch
      - switch.pi3_vestibule_switch
      - switch.pi3_hall_downstairs_switch
