alias: 'Hall mode bedtime reset'
initial_state: 'on'
trigger:
  - platform: state
    entity_id: input_select.hall
    to: 'Night on'
    for: '00:03:00'
  - platform: state
    entity_id: input_select.hall
    to: 'Dim'
    for: '00:03:00'
  - platform: state
    entity_id: input_select.hall
    to: 'On'
    for: '00:03:00'
  - platform: state
    entity_id: input_select.hall
    to: 'Day on'
    for: '00:03:00'
condition:
  - condition: state
    entity_id: input_boolean.bedtime
    state: 'on'
action:
  - service: input_select.select_option
    data:
      entity_id: input_select.hall
      option: 'Bedtime'
