initial_state: 'on'
alias: 'person3 awake'
trigger:
  - platform: state
    entity_id: input_boolean.person3_in_bed
    to: 'off'
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.person3_is_awake
  - service: script.person3_travel_sensor
