alias: 'Front door open'
initial_state: 'on'
trigger:
  - platform: state
    entity_id: binary_sensor.pi3_front_door_sensor
    to: 'on'
action:
  - service: script.scan_bt_arrive
  - service: automation.turn_off
    data:
      entity_id: automation.garage_open_nobody_home
