alias: 'Garage open nobody home'
initial_state: 'off'
trigger:
  - platform: state
    entity_id: binary_sensor.pi3_garage_closed_car_sensor
    to: 'on'
action:
  - service: notify.person2
    data:
      message: "Nobody is home right now, turn off the alarm"
      data:
        priority: '1'
        sound: 'siren'
        device: 'MyPhone'
