alias: 'Rob away Garage open'
initial_state: 'on'
trigger:
  - platform: state
    entity_id: input_boolean.person2_home
    to: 'off'
condition:
  - condition: state
    entity_id: binary_sensor.pi3_garage_closed_car_sensor
    state: 'on'
action:
  - service: notify.person2
    data:
      message: "You idiot, you left the garage door open"
      data:
        priority: '1'
        sound: 'siren'
        device: 'MyPhone'
