initial_state: 'on'
alias: 'Living room night on'
trigger:
  - platform: state
    entity_id: input_boolean.living_room_occupied
    to: 'on'
  - platform: state
    entity_id: switch.pi3_cabinet_light_switch
    to: 'on'
  - platform: numeric_state
    entity_id: sensor.pi3_living_room_multi_luminance
    below: 12
    for:
      minutes: 5
  - platform: numeric_state
    entity_id: sensor.pi3_living_room_multi_luminance
    below: 10
    for:
      minutes: 1
  - platform: numeric_state
    entity_id: sensor.pi3_living_room_multi_luminance
    below: 6
  - platform: numeric_state
    entity_id: sensor.pi3_living_room_multi_luminance
    below: 1
condition:
  - condition: and
    conditions:
    - condition: template
      value_template: "{{ not is_state('input_select.living_room','Night on') }}"
    - condition: state
      entity_id: input_boolean.living_room_occupied
      state: 'on'
    # Bear light off, and dull, or bear light on and brighter
    - condition: or
      conditions:
      - condition: and
        conditions:
        - condition: state
          entity_id: switch.pi3_cabinet_light_switch
          state: 'off'
        - condition: numeric_state
          entity_id: sensor.pi3_living_room_multi_luminance
          below: 12
      - condition: and
        conditions:
        - condition: state
          entity_id: switch.pi3_cabinet_light_switch
          state: 'on'
        - condition: numeric_state
          entity_id: sensor.pi3_living_room_multi_luminance
          below: 20
    # Didn't just turn the lights off
    - condition: template
      value_template: "{{ (as_timestamp(now()) - as_timestamp(states.switch.pi3_cabinet_light_switch.last_updated)) | int > 120 }}"
action:
  - service: notify.logfile
    data_template:
      message: >
        Night on triggered at {{ now() }} by {{ trigger.entity_id }}, was {{ trigger.from_state.state }} is {{ trigger.to_state.state }}
          Light level is {{ states('sensor.pi3_living_room_multi_luminance') }}
  - service: input_select.select_option
    data:
      entity_id: input_select.living_room
      option: 'Night on'
  - service: input_boolean.turn_off
    entity_id: input_boolean.livingroom_lights_auto
