initial_state: 'on'
alias: 'Living room day on'
trigger:
  - platform: state
    entity_id: input_boolean.living_room_occupied
    to: 'on'
    for: '00:00:02'
  - platform: numeric_state
    entity_id: sensor.pi3_living_room_multi_luminance
    below: 18
    for:
      minutes: 5
  - platform: numeric_state
    entity_id: sensor.pi3_living_room_multi_luminance
    below: 16
    for:
      minutes: 1
  - platform: numeric_state
    entity_id: sensor.pi3_living_room_multi_luminance
    above: 11
    for:
      minutes: 10
condition:
  - condition: and
    conditions:
    - condition: template
      value_template: "{{ not is_state('input_select.living_room','Day on') and not is_state('input_select.living_room','Night on')}}"
    # Room is dark, but not too dark
    - condition: numeric_state
      entity_id: sensor.pi3_living_room_multi_luminance
      below: 25
      above: 11
    - condition: state
      entity_id: input_boolean.living_room_occupied
      state: 'on'
    # Didn't just turn the lights off
    - condition: template
      value_template: "{{ (as_timestamp(now()) - as_timestamp(states.switch.pi3_cabinet_light_switch.last_updated)) | int > 120 }}"
action:
  - service: notify.logfile
    data_template:
      message: >
        Day on triggered at {{ now() }} by {{ trigger.entity_id }}, was {{ trigger.from_state.state }} is {{ trigger.to_state.state }}
          Light level is {{ states('sensor.pi3_living_room_multi_luminance') }}
  - service: input_select.select_option
    data:
      entity_id: input_select.living_room
      option: 'Day on'
  - service: input_boolean.turn_off
    entity_id: input_boolean.livingroom_lights_auto
