initial_state: 'on'
alias: 'Living room occupied'
trigger:
  - platform: state
    entity_id: media_player.samsung_tv
    to: 'on'
    for:
      minutes: 5
  - platform: state
    entity_id: media_player.cast_living_room_tv
    to: 'playing'
    for:
      minutes: 5
  - platform: state
    entity_id: media_player.cast_living_room_tv
    to: 'off'
    from: 'unavailable'
    for:
      minutes: 5
  - platform: state
    entity_id: device_tracker.livingroom_chromecast
    to: 'home'
    for:
      minutes: 5
  - platform: state
    entity_id: media_player.living_room
    to: 'playing'
    for:
      minutes: 5
  - platform: state
    entity_id: media_player.samsung_tv
    to: 'on'
  - platform: state
    entity_id: media_player.cast_living_room_tv
    to: 'playing'
  - platform: state
    entity_id: media_player.cast_living_room_tv
    to: 'off'
    from: 'unavailable'
  - platform: state
    entity_id: device_tracker.livingroom_chromecast
  - platform: state
    entity_id: device_tracker.livingroom_chromecast
    to: 'home'
  - platform: state
    entity_id: media_player.living_room
    to: 'playing'
  - platform: state
    entity_id: binary_sensor.pi3_living_room_motion
    to: 'on'
condition:
  condition: and
  conditions:
    # Room must currently be not occupied
    - condition: state
      entity_id: input_boolean.living_room_occupied
      state: 'off'
    # There's either been motion in the last few minutes, or we're awake
    - condition: or
      conditions:
      # There's been motion in the last 3 minutes
      - condition: template
        value_template: "{{ ( as_timestamp(now()) - as_timestamp(states.binary_sensor.pi3_living_room_motion.last_updated) ) < 180 }}"
      # We're awake
      - condition: state
        entity_id: input_boolean.bedtime
        state: 'off'
    # Some form of media is active
    - condition: or
      conditions:
      # Sonos
      - condition: state
        entity_id: media_player.living_room
        state: 'playing'
      - condition: and
        conditions:
        # TV
        - condition: state
          entity_id: media_player.samsung_tv
          state: 'on'
        # Chromecast
        - condition: or
          conditions:
          - condition: state
            entity_id: media_player.cast_living_room_tv
            state: 'playing'
          - condition: state
            entity_id: media_player.cast_living_room_tv
            state: 'off'
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.living_room_occupied
