- platform: template
  sensors:
    last_opened:
      friendly_name: 'Last opened'
      entity_id:
        - binary_sensor.pi3_front_door_sensor
        - binary_sensor.pi3_patio_door_left_sensor
        - binary_sensor.pi3_utility_door_exterior_sensor
        - binary_sensor.pi3_garage_closed_bike_sensor
        - binary_sensor.pi3_garage_closed_car_sensor
        - binary_sensor.vestibule_window_front
        - binary_sensor.vestibule_window_side
        - binary_sensor.family_window_left
        - binary_sensor.family_window_right
        - binary_sensor.patio_window_left
        - binary_sensor.patio_window_right
        - binary_sensor.guest_bedroom_window_left
        - binary_sensor.guest_bedroom_window_right
        - binary_sensor.master_window_ensuite
        - binary_sensor.master_window_left
        - binary_sensor.master_window_right
        - binary_sensor.office_window
        - binary_sensor.spare_bedroom_window_left
        - binary_sensor.spare_bedroom_window_right
        - binary_sensor.second_bedroom_window_ensuite
        - binary_sensor.second_bedroom_window_left
        - binary_sensor.second_bedroom_window_right
        - binary_sensor.bathroom_window
      value_template: >-
        {%- set sensors = [ states.binary_sensor.pi3_front_door_sensor, states.binary_sensor.pi3_patio_door_left_sensor, states.binary_sensor.pi3_utility_door_exterior_sensor, states.binary_sensor.pi3_garage_closed_bike_sensor, states.binary_sensor.pi3_garage_closed_car_sensor, states.binary_sensor.vestibule_window_front, states.binary_sensor.vestibule_window_side, states.binary_sensor.family_window_left, states.binary_sensor.family_window_right, states.binary_sensor.patio_window_left, states.binary_sensor.patio_window_right, states.binary_sensor.guest_bedroom_window_left, states.binary_sensor.guest_bedroom_window_right, states.binary_sensor.master_window_ensuite, states.binary_sensor.master_window_left, states.binary_sensor.master_window_right, states.binary_sensor.office_window, states.binary_sensor.spare_bedroom_window_left, states.binary_sensor.spare_bedroom_window_right, states.binary_sensor.second_bedroom_window_ensuite, states.binary_sensor.second_bedroom_window_left, states.binary_sensor.second_bedroom_window_right, states.binary_sensor.bathroom_window ] %}
        {% for sensor in sensors %}
          {% if as_timestamp(sensor.last_changed) == as_timestamp(sensors | map(attribute='last_changed') | max) %}
            {{ sensor.name }}
          {% endif %}
        {% endfor %}
