- platform: template
  sensors:
    master_ensuite_change_rate:
      entity_id: sensor.master_ensuite_humidity_stats
      value_template: "{{ state_attr('sensor.master_ensuite_humidity_stats', 'change_rate') }}"
      unit_of_measurement: "%"
