alias: 'person1 awake'
initial_state: 'on'
trigger:
  - platform: state
    entity_id: input_boolean.person1_in_bed
    to: 'off'
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.person1_is_awake
  - service: script.person1_travel_sensor
