alias: 'Adults returned'
initial_state: 'on'
trigger:
  - platform: state
    entity_id: 
      - input_boolean.person3_home
      - input_boolean.person2_home
    to: 'on'
condition:
  - condition: state
    entity_id: input_boolean.adults_away
    state: 'on'
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.adults_away
