alias: 'All away'
initial_state: 'on'
trigger:
  - platform: state
    entity_id: 
      - input_boolean.person3_home
      - input_boolean.person2_home
      - input_boolean.person1_home
      - input_boolean.family_room_occupied
      - input_boolean.living_room_occupied
      - input_boolean.office_occupied
    to: 'off'
condition:
  condition: and
  conditions:
    # We're all away
    - condition: state
      entity_id: input_boolean.person3_home
      state: 'off'
    - condition: state
      entity_id: input_boolean.person2_home
      state: 'off'
    - condition: or
      conditions:
      # Either the phone or tablet are away, or the family room isn't occupied
      - condition: state
        entity_id: group.person_person1_tablet
        state: 'not_home'
      - condition: state
        entity_id: input_boolean.person1_home
        state: 'off'
      - condition: state
        entity_id: input_boolean.family_room_occupied
        state: 'off'
    - condition: state
      entity_id: input_boolean.family_room_occupied
      state: 'off'
    # Rooms not occupied
    - condition: state
      entity_id: input_boolean.living_room_occupied
      state: 'off'
    - condition: state
      entity_id: input_boolean.office_occupied
      state: 'off'
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.all_away
