alias: 'All returned'
initial_state: 'on'
trigger:
  - platform: state
    entity_id: 
      - input_boolean.person3_home
      - input_boolean.person1_home
      - input_boolean.person2_home
    to: 'on'
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.all_away
