alias: 'Extractor on'
initial_state: 'on'
trigger:
  - platform: template
    value_template: >-
      {{ states('sensor.master_ensuite_humidity')|int > (((states('sensor.bathroom_humidity')|int + states('sensor.pi3_office_multi_relative_humidity')|int + states('sensor.second_bedroom_ensuite_humidity')|int)/3)+20) }}
    for: '00:05:00'
condition:
  - condition: state
    entity_id: input_boolean.office_occupied
    state: 'on'
action:
  - service: homeassistant.turn_on
    entity_id: automation.extractor_off
