alias: 'Extractor off'
initial_state: 'off'
trigger:
  - platform: template
    value_template: >-
      {{ states('sensor.master_ensuite_humidity')|int < (((states('sensor.bathroom_humidity')|int + states('sensor.pi3_office_multi_relative_humidity')|int + states('sensor.second_bedroom_ensuite_humidity')|int)/3)+10) }}
    for: '00:05:00'
condition:
  - condition: state
    entity_id: input_boolean.office_occupied
    state: 'on'
action:
  - service: homeassistant.turn_off
    entity_id: automation.extractor_off
  - service: script.notify_person2_at_home
    data:
      message: "You can turn the extractor fan off now"
