initial_state: 'on'
alias: 'Rob not driving'
trigger:
  - platform: event
    event_type: tasker_webhook
    event_data:
      who: person2
condition: 
  # Leaving, the car
  - condition: template
    value_template: >-
      {{ ',Exit Car,' in trigger.event.data.what }}
  # Driving
  - condition: state
    entity_id: input_boolean.person2_driving
    state: 'on'
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.person2_driving
  - wait_template: >-
      {{ ( as_timestamp(now()) - as_timestamp(states.device_tracker.person2_mobile_gps.last_updated)|float)|float < 60 }}
  - service: script.update_car_location
