alias: 'Rob awake'
initial_state: 'on'
trigger:
  - platform: state
    entity_id: input_boolean.person2_in_bed
    to: 'off'
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.person2_is_awake
  - service: script.person2_travel_sensor
