initial_state: 'on'
alias: 'Rob home'
trigger:
  - platform: state
    entity_id: 
      - device_tracker.40_4e_36_24_53_15
      - device_tracker.person2_bt_mobile
      - device_tracker.person2_bt_front_mobile
    to: 'home'
  - platform: homeassistant
    event: start
condition:
  - condition: numeric_state
    entity_id: group.person_person2
    above: 0
    value_template: "{{ dict((states|selectattr('entity_id', 'in', state_attr('group.person_person2', 'entity_id'))|list)|groupby('state'))['home']|count }}"
action:
  - service: script.person2_home
