initial_state: 'on'
alias: 'Rob driving'
trigger:
  - platform: event
    event_type: tasker_webhook
    event_data:
      who: person2
condition: 
  # In the car
  - condition: template
    value_template: >-
      {{ ',Car,' in trigger.event.data.what }}
  # Not driving
  - condition: state
    entity_id: input_boolean.person2_driving
    state: 'off'
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.person2_driving
