alias: 'person4 away'
initial_state: 'on'
trigger:
  - platform: numeric_state
    entity_id: proximity.person4_home
    above: 2
  - platform: state
    entity_id:
      - device_tracker.00_1d_29_a5_49_ae
      - device_tracker.person4_bt_front_mobile
      - device_tracker.person4_bt_mobile
    to: 'not_home'
  - platform: homeassistant
    event: start
condition:
  - condition: numeric_state
    entity_id: group.person_person4
    below: 2
    value_template: "{{ dict((states|selectattr('entity_id', 'in', state_attr('group.person_person4', 'entity_id'))|list)|groupby('state'))['home']|count }}"
  # Either a door just opened/closed, or we're far, far away
  - condition: or
    conditions:
    # An exit door recently opened or closed, or motion in the vestibule
    - condition: template
      value_template: >-
        {{ ((as_timestamp(now()) - as_timestamp(states.binary_sensor.pi3_front_door_sensor.last_updated)) | int < 300) 
          or 
           ((as_timestamp(now()) - as_timestamp(states.binary_sensor.pi3_garage_closed_car_sensor.last_updated)) | int < 300) 
          or
           ((as_timestamp(now()) - as_timestamp(states.binary_sensor.vestibule_occupancy.last_updated)) | int < 300) 
        }}
    # All away, and not near
    - condition: and
      conditions:
      - condition: state
        entity_id: group.person_person4
        state: 'not_home'
      - condition: numeric_state
        entity_id: proximity.person4_home
        above: 2
action:
  - service: script.person4_away
