alias: 'HA started'
initial_state: 'on'
trigger:
  platform: homeassistant
  # Event can also be 'shutdown'
  event: start
action:
  - service: script.notify_person2
    data_template:
      message: "Home Assistant has started on Vision ({{ utcnow() }})"
