initial_state: 'on'
alias: 'Remote ping'
trigger:
  - platform: state
    entity_id: sensor.date_time
action:
  - wait_template: >-
      {{ states('sensor.date_time') == states('sensor.pi3_date_time') }}
    timeout: '00:01:00'
    continue_on_timeout: 'true'
  - condition: template
    value_template: "{{ states('sensor.date_time') != states('sensor.pi3_date_time') }}"
  - service: notify.logfile
    data:
      message: "SENDME Looks like the remote link has failed"
  - service: automation.turn_off
    entity_id: automation.remote_ping
